# Copyright (c) Jupyter Development Team.
# Distributed under the terms of the Modified BSD License.

# JupyterHub docker compose configuration file
include:
  - path:
    - docker-compose.yml
    - override.dev.yml