# -*- mode: yaml -*-
# vim: ft=yaml:

[global]
  i: 127.0.0.1,::1
  rproxy: 1
  xff-hdr: x-real-ip
  xf-proto: https
  xf-proto-fb: https
  hist: ~/.cache/copyparty/
  http-only
  gauto: 70
  e2dsa
  no-hash: .*
  no-idx: ^\..*$

[/]         # create a volume at "/" (the webroot), which will
  ~
  accs:
    rw: *